//Authentification
const SET_AUTHENTIFICATION_TOKEN = 'SET_AUTHENTIFICATION_TOKEN'
const REMOVE_AUTHENFICATION_TOKEN = 'REMOVE_AUTHENTIFICATION_TOKEN'
const GET_USER_PROFILE = 'GET_USER_PROFILE'



export  {
    SET_AUTHENTIFICATION_TOKEN,
    REMOVE_AUTHENFICATION_TOKEN,
    GET_USER_PROFILE
}